# Generated by Django 3.2.3 on 2021-06-30 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='self.request.user.profile.image', upload_to='uploads/')),
                ('fileUpload', models.FileField(upload_to='uploads/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, default='No Description', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
