# Generated by Django 3.2.3 on 2021-06-30 07:26

import Vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0002_alter_vaultdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultdata',
            name='fileUpload',
            field=models.FileField(upload_to=Vault.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vaultdata',
            name='image',
            field=models.ImageField(default='self.request.user.profile.image', upload_to=Vault.models.user_directory_path),
        ),
    ]
