# Generated by Django 3.2.3 on 2021-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0003_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_secret_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='User Secret Key'),
        ),
    ]
