# Generated by Django 3.2.3 on 2021-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0005_delete_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nonce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nonce'),
        ),
    ]
